server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:C:/Users/Wellington/demodb.db
    username: sa
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./data/index