DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS INGREDIENT_DESCRIPTION;

CREATE TABLE USERS (
	uuid UUID default random_uuid() NOT NULL,
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(50),
	gender CHARACTER,
	email VARCHAR(50),
	password VARCHAR(100),
	created_at TIMESTAMP(1),
	PRIMARY KEY (uuid)
);

CREATE TABLE RECIPE (
	uuid UUID default random_uuid() NOT NULL,
	uuid_user UUID NOT NULL,
	title VARCHAR(50) NOT NULL,
	prep_time SMALLINT NOT NULL,
	cook_time SMALLINT NOT NULL,
	serving SMALLINT NOT NULL,
	instructions CHARACTER LARGE OBJECT(10000) NOT NULL,
	ingredients CHARACTER LARGE OBJECT (5000) NOT NULL,
	notes CHARACTER LARGE OBJECT(1000),
	occasion CHARACTER VARYING(20) NOT NULL,
	recipe_type CHARACTER VARYING(20),
	PRIMARY KEY (uuid)
);

--CREATE TABLE INGREDIENT_DESCRIPTION (
--	uuid UUID default random_uuid() NOT NULL,
--	name VARCHAR(50) NOT NULL,
--	ingredient_type VARCHAR(20) NOT NULL,
--	measure CHARACTER VARYING(20) NOT NULL,
--	amount SMALLINT NOT NULL,
--	PRIMARY KEY (uuid)
--);